### PR TITLE
Fix when pyyaml has interpreted line as a dictionary

### PR DESCRIPTION
**Pull request by tdesvenain**

### CODE REVIEW

**Comment by tdesvenain** [comment]
Hi, did you have a look at this request ?

Thanks

Thomas

**Comment by sampwing** [comment]
@tdesvenain ,

Yes- thanks for the pr, my apologies for the delay.  I tried to replicate this with my version of pyyaml but I could not replicate.  Could you let me know what versin of pyyaml you're running? 

I was using this input:

    app: 
      extra_hosts: 192.1.2.3:dockerhost

    app2: 
      extra_hosts:
        - 192.1.2.3:dockerhost

**Comment by tdesvenain** [comment]
Hi !

my conf likes :

php:
    (...)
    extra_hosts:
    - dev-hub.content-square.fr: 192.168.0.55
    - dev-uxanalytics.content-square.fr: 192.168.0.55
    - dev-ps.content-square.fr: 192.168.0.55
    - dev-ergotest.content-square.fr: 192.168.0.55
    - dev-publicitest.content-square.fr: 192.168.0.55

my PyYAML ver is :

PyYAML-3.11

Thanks !

2015-01-26 4:23 GMT+01:00 Sam Wing <notifications@github.com>:

> @tdesvenain <https://github.com/tdesvenain> ,
>
> Yes- thanks for the pr, my apologies for the delay. I tried to replicate
> this with my version of pyyaml but I could not replicate. Could you let me
> know what versin of pyyaml you're running?
>
> I was using this input:
>
> app:
>   extra_hosts: 192.1.2.3:dockerhost
>
> app2:
>   extra_hosts:
>     - 192.1.2.3:dockerhost
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sampwing/fig/pull/1#issuecomment-71410538>.
>



-- 
Thomas Desvenain

Téléphone : 09 51 37 35 18

**Comment by sampwing** [comment]
Thomas,
Ah gotcha, I didn't catch adding the spaces after the separators with the hostnames - but it makes sense. 
Thanks!
Sam

**Pull request merged**
